### ISSUE TITLE
Service point list in sidebar does not update on search

### ISSUE THREAD

**Issue by villermen** [SendCloud/spp-integration-example#10]
1. Open the SPP and note that the service points listed in the sidebar are also the ones shown as pins on the map view.
2. Navigate to another area using the search bar.
3. You will be moved to the searched area, but the listed service points will not change unless you click on one in the new area.

Illustrated in a video: [spp-static.mp4](https://slack-files.com/T02FYTTUL-F014KUTQ57W-915bea6a3b)

Also note that in the video the map is not updated correctly the first time moving to "friesland". Might be related, might be a different issue entirely.

**Comment by erickwilder** [comment]
Thanks for reporting this @villermen 
We'll take a look at this and keep you updated

**Comment by villermen** [comment]
@erickwilder Can I expect this to be addressed anytime soon?

**Comment by holymountain92** [comment]
hi @villermen , we have been working on it but not quite solved it unfortunately. I don't expect to have a solution this month.

**Comment by villermen** [comment]
@holymountain92 No problem. Just knowing that it's still on your radar somewhere is enough =)

**Comment by erickwilder** [comment]
Hello @villermen we made some changes in the way we repaint points in the map. May you check if this is now working for you?

**Comment by villermen** [comment]
@erickwilder Do I have to change anything on my end (e.g., the external script URL)? I'm still getting nearly same result as of right now: [spp-static2.mp4](https://slack-files.com/T02FYTTUL-F01EPTN4ZKR-4d5528f039)

**Comment by erickwilder** [comment]
No you don't have to change anything on your side. Thanks for the video in the report. I'll let the team know because this is different than what we changed. Just for context, there is a zoom level in the map that we stop loading service points and I think we should better adjust it.

**Comment by philipp-rudloff-sendcloud** [comment]
As far as I can tell, this issue has been fixed in the meantime.

Previously, the service point list would only update at the time the search produced the list of results (between 0 or 5 results). It would always select the first result to do that. If the user clicked on any of the other results, the map and the resulting list would become out of sync.

Now, the list is also updated when selecting one of the suggestions produced by a search.
