### ISSUE TITLE
Search is not localized

### ISSUE THREAD

**Issue by villermen** [SendCloud/spp-integration-example#14]
The "City or Postal Code" placeholder and the "Location not found" tooltip are always displayed in English, regardless of locale. This can easily be reproduced in the integration example. The following is a screenshot with country "de" and locale "de-de":

![image](https://user-images.githubusercontent.com/1106303/111996507-608a0280-8b1a-11eb-9c74-941fd32c2b3c.png)

**Comment by philipp-rudloff-sendcloud** [comment]
This issue has been fixed.
