### ISSUE TITLE
How to Filter shop_type

### ISSUE THREAD

**Issue by magic-77** [SendCloud/spp-integration-example#15]
Is it possible to send a filter parameter for "shop_type" to get only certain types?

**Comment by philipp-rudloff-sendcloud** [comment]
Currently, there is no filter for a service point’s `shop_type` field. For which use case would it be helpful to you to be able to limit the listed service points by shop type?

**Comment by magic-77** [comment]
Hi @philipp-rudloff-sendcloud this is possible when using this API Endpoint
```https://servicepoints.sendcloud.sc/api/v2/service-points/```

I have written an customized Service Point Picker in JS where i'm using this Endpoint.
After receiving the data i can ```filter``` the type of packstation like this:

this is inside ```then``` Function
```
return _.filter(data, function (packstation)
{
    // -1 means that this record is not present
    return ['packStation'].indexOf(packstation.shop_type) !== -1; 
});
```

I can share my Plugin with you, if you're interested in

**Comment by philipp-rudloff-sendcloud** [comment]
Hello again @magic-77. The service points API now supports a new filter parameter `shop_type`. The API documentation was updated accordingly: [service points API: find service points](https://docs.sendcloud.sc/api/v2/service-points/#find-service-points). The [API integration demo page](https://sendcloud.github.io/spp-integration-example/) was also updated.

**Comment by magic-77** [comment]
Hello @philipp-rudloff-sendcloud, thank you for your support. I will integrate the new feature with us
