### ISSUE TITLE
Authentication credentials were not provided

### ISSUE THREAD

**Issue by hamcher** [SendCloud/spp-integration-example#18]
Hi, i tested this example with a valide api but i have this message *Authentication credentials were not provided.*
i thing because the access token not sent in the header but in the body of the request 
```js
headers = {
  'Authorization': 'AccessToken YOUR_API_KEY'
}
```

**Comment by philipp-rudloff-sendcloud** [comment]
I’m closing this issue as there are no other reports of authentication issues with the service points API.
