### ISSUE TITLE
failureCallback is not a function

### ISSUE THREAD

**Issue by rauwebieten** [SendCloud/spp-integration-example#2]
TypeError: failureCallback is not a function[Meer info] api.min.js:22:104
    onWindowMessage https://embed.sendcloud.sc/spp/1.0.0/api.min.js:22

Happens on pageload, also on your live example page: https://sendcloud.github.io/spp-integration-example/

**Comment by tomdeleu** [comment]
I have exactly the same issue.  When digging deeper, this seems to be the culprit: https://cl.ly/7b700bb1e8c1

Besides the error; everything seems to work fine. I can actually use the Servicepoint picker. But not comfortable seeing the error of course.

**Comment by erickwilder** [comment]
Some recent changes fix the issue. Please let use know if this is still happening
