### ISSUE TITLE
Picker doesn't work in IE11

### ISSUE THREAD

**Issue by villermen** [SendCloud/spp-integration-example#5]
1. Open the integration example in IE11: https://sendcloud.github.io/spp-integration-example/
2. Fill in a valid public API key and click on <kbd>Select Service Point</kbd> in the "Basic Example" section.
3. Only the layout of the picker will pop up and the console will list an (unhelpful) error:

![image](https://user-images.githubusercontent.com/1106303/75355752-434f1a00-58af-11ea-9485-beddb87c4544.png)

```
SCRIPT1014: Invalid character
output.c598f3ec1be2.js (2,612)
```

I'm creating an issue for this as the README claims that the example supports IE10 and up.

**Comment by erickwilder** [comment]
Thanks for your report. 

Indeed the project was initially built to support IE10+. We'll both work on a fix for this and better check what versions we intend to support and communicate upfront with a grace period if/when we decided to remove support for certain browser/version.

Currently, Internet Explorer corresponds to around 1% of all traffic of our service point map. Usually our policy is to drop support if this number goes bellow that number. Even though we are _not dropping its support right now_ this could be the case in the near future.

**Comment by erickwilder** [comment]
Based on all the data we got this got little to no business support and we decided to officially _drop Internet Explorer_ support. The documentation here already reflects this decision
