### ISSUE TITLE
Multiple layered service point pickers

### ISSUE THREAD

**Issue by i-n-g-m-a-r** [SendCloud/spp-integration-example#8]
It's possible to open multiple ssp's layered on top of each other causing bugs.
Previously opened layers should be cleaned up automatically before opening a new layer.

**Comment by i-n-g-m-a-r** [comment]
wakker worden @erickwilder

**Comment by erickwilder** [comment]
May you give me a little bit of context on this one? Perhaps if you attach some screenshots and/or reproducible steps would be helpful.

Thanks for reporting the issue

**Comment by i-n-g-m-a-r** [comment]
The context is that when calling this function multiple times:
```javascript
function openServicePointPicker(api_key, country, language, postal_code, carriers, service_point_id) {
  var config = {
    'apiKey': api_key,
    'country': country,
    'postalCode': postal_code,
    'language': language,
    'carriers': carriers || "",
    'servicePointId': service_point_id || 0
  }
  sendcloud.servicePoints.open(
    config,
    function(obj) {},
    function(errors) {}
  );
}
```
multiple maps are stacked on top of each other while the maps should be replaced.
The implementation does not check whether a placeholder already exists, so that first the existing placeholder is removed before adding a new placeholder.
Or even better, probably the existing placeholder can be reused.

**Comment by philipp-rudloff-sendcloud** [comment]
For this, the `sendcloud.servicePoints` now holds another property called `close`. When called, it removes the injected `iframe` from the page. Considering that causing the map to be injected is done by someone integrating with the service point picker via API integration, it’s reasonable to also let them control the removal part of the process.
